services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: finsight1_user
      POSTGRES_PASSWORD: finsight1_password
      POSTGRES_DB: finsight1_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: